# Generated by Django 3.1 on 2020-08-16 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0002_auto_20200816_1408'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Greeting',
        ),
        migrations.AlterField(
            model_name='subscribe',
            name='date_added',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
